# Generated by Django 5.1.6 on 2025-05-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installed_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Requested Service', 'Requested Service'), ('Yearly Service', 'Yearly Service')], max_length=50)),
                ('request_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('client_description', models.TextField(blank=True, null=True)),
                ('tech_description', models.TextField(blank=True, null=True)),
                ('installed_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='installed_devices.installeddevice')),
            ],
        ),
    ]
